openapi: 3.1.0
info:
  title: api
  version: '1.0'
paths:
  /deco:
    get:
      operationId: get-test
      responses:
        '200':
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: Example result