openapi: 3.1.0
info:
  title: Test endpoints for Deco
  version: '1.0'
  description: ''
paths:
  /api:
    get:
      operationId: get-deco
      responses:
        '200':
          description: REST response
          content:
            text/plain:
              schema:
                type: string
                example: "Hello from Deco \U0001F389"
              examples:
                example-1:
                  summary: This is a valid example
                  value: Hello from example response 1️⃣
                example-2:
                  summary: This is a valid example
                  value: Hello from example response 2️⃣
                example-3:
                  summary: This is a valid example
                  value: Hello from example response 3️⃣
      description: Test endpoint
      summary: ''
    parameters: []
